### ISSUE TITLE
allow extra_data in run_assessment

### ISSUE THREAD

**Issue by RobFryer** [osparcomm/HARSAT#382]
Allow VDS estimates and confidence limits (which are created in a preliminary set of function calls #124) to be passed explicitly into run_assessment.  These are currently called biota.VDS.estimates and biota.VDS.cl.

**Comment by RobFryer** [comment]
@morungos I've been working on this and encountering some very bizarre error messages associated with the parallel processing - for example, I get the following even though there is no reference to `thetaID` in the code (I did have it as a variable in some of my changes, but subsequently deleted them all).
```
Error in checkForRemoteErrors(val) :
one node produced an error: argument "thetaID" is missing, with no default
```
I've reverted to the original code and am going to build things up again, but I might need your expertise if I can't find a way through.  Will report back in the next couple of days. The joys!

**Comment by morungos** [comment]
@RobFryer Have you tried it without parallel? There is a possibility that you get more of a backtrack that way, just maybe. I'll happily dive in and peek if you like.

**Comment by RobFryer** [comment]
@morungos Annoyingly, it was working beautifully without parallel!  I'll see where I get to and if I can't crack it I'll send you a test case (that doesn't work).

**Comment by morungos** [comment]
If it only fails with parallel I should definitely take a look, so a test case would be very helpful.

**Comment by RobFryer** [comment]
@morungos It seems to be something very dark. `clusterExport` is finding versions of e.g. `get_index` and `imposex.class` that were modified several pull requests ago.  These are certainly not the current versions (which are accessed correctly when `parallel = FALSE`).  I wonder if this is some legacy issue related to when harsat went public.  I set up a new fork, but continued working with my old R Project (which seemed to be tracking the new fork acceptably).  I guess the next thing to try is deleting my old R Project and setting up a new one.

**Comment by morungos** [comment]
@RobFryer I bet it's because the package is installed as well as running in development, and the nodes are incorrectly finding the installed one, not the development one. Try uninstalling the package via R Studio. I'll see if there's a better way we can do that, but it any installed package user ought to be fine. If that stops it behaving oddly it's a bug to track independently even if we can't easily make a fix.

**Comment by morungos** [comment]
I'll also note that this also probably works fine when run as unit tests. I don't know how this is currently being run, but if you try command line shenanigans and have an installed package, it could well go belly up. I am not sure we should even try to address that. I think this behaviour is a consequence of a previous fix which also attempted to make things work for developer command line usage. 

If you send me a test case, which will likely also need to cover how it should be run, I'll look, but I don't think we ought to spend too long on this, since package users should probably be unaffected.

**Comment by morungos** [comment]
@RobFryer Well, I am glad that fixed it for now. But I'd still think we should probably make an issue to explore this some time. I don't want to invest too much effort, but having an issue at least acknowledges we are aware of this. And I might play with options for testing it some time.
