### ISSUE TITLE
Choose strategy re where to store and locate reference table sets for stakeholder organisations (AMAP, OSPAR, HELCOM etc)

### ISSUE THREAD

**Issue by hansmy** [osparcomm/HARSAT#398]
On a related issue, a decision still needs to be agreed) on how organizational ‘reference table set’ repositories will be managed, and where these will be located.  To discuss and agree on this asap

**Comment by morungos** [comment]
Here's what I'd say:

1. The only logical place for an organization's official reference table set is in a repository controlled only by that organization, probably alongside the data. `harsat` should not become responsible for, or on the critical path for, these files.
2. Today, `harsat` only builds its example datasets, which are where the reference tables are exposed, from its repository, because no other organizations have repositories yet
3. We could, in future, pull and build example data sets, including reference table sets, from other repositories -- if they exist -- and we can use those others as sources for the `harsat` datasets/examples pages. This is probably the right strategy, but we cannot really do it immediately. There is some architectural work, and as I said, the repositories need to exist. 
4. In practice, because we did plan this fairly carefully, an organization's reference table set will override anything coming from `harsat`. So there's no problem with making "best efforts" to keep the `harsat` tables updated without making everyone else totally dependent on the `harsat` tables. That allows is to grow from where we are now, to an ideal long-term situation as in 3 above.

**Comment by morungos** [comment]
I discussed this with @swamap today, and our feeling is that "official" reference table sets will not be part of the main repository. This allows organizations a free hand to manage their data tables any way they see fit. The **example** reference table sets can and will stay as they are, within the main repository, where they can be used to exercise the code needed for the different assessments. 

I'd recommend that folks use Github for their reference table sets, but I don't think we can or should enforce this, because if we do, we are simply putting ourselves at risk of dependencies. So, for now, the "strategy" is: do what you need to do, wherever you like. I can and will help folks get set up with Github infrastructures if they want to use something like our packaging processes to set this up.

And on that note, I'll close this issue. We can re-open if needed.
